import React from 'react';
import { ScrollView, Text, View } from 'react-native';
import tw from 'twrnc';
import { commonConstants } from '../commonConstants';

export const TncContainer = () => {
  const { appName, companyName, companyAddress, contactEmail, domainName,jurisdiction } = commonConstants.compInfo;


  return (
    <ScrollView style={tw`bg-white dark:bg-[#151718] min-h-full p-6`}>
      <Text style={tw`text-2xl font-bold text-black dark:text-white mb-8`}>
        Terms and Conditions
      </Text>

      <View style={tw`space-y-6`}>
        <Text style={tw`text-black dark:text-white leading-6`}>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </Text>

        <Text style={tw`text-black dark:text-white leading-6`}>
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of domain name {domainName}{' '}
          ("Website"), including the related mobile site and mobile application
          (hereinafter referred to as "Platform").
        </Text>

        <Text style={tw`text-black dark:text-white leading-6`}>
          The Platform is owned by {companyName}, a company incorporated under
          the Companies Act, 1956 with its registered office at {companyAddress}{' '}
          (hereinafter referred to as "Platform Owner", "we", "us", "our").
        </Text>

        <Text style={tw`text-black dark:text-white leading-6`}>
          Your use of the Platform and services and tools are governed by the
          following terms and conditions ("Terms of Use") as applicable to the
          Platform including the applicable policies which are incorporated
          herein by way of reference. If You transact on the Platform, You shall
          be subject to the policies that are applicable to the Platform for
          such transaction. By mere use of the Platform, You shall be
          contracting with the Platform Owner and these terms and conditions
          including the policies constitute Your binding obligations, with
          Platform Owner.
        </Text>

        <Text style={tw`text-black dark:text-white leading-6`}>
          These Terms of Use relate to your use of our website, goods (as
          applicable) or services (as applicable) (collectively, "Services").
          Any terms and conditions proposed by You which are in addition to or
          which conflict with these Terms of Use are expressly rejected by the
          Platform Owner and shall be of no force or effect.
        </Text>

        <Text style={tw`text-black dark:text-white leading-6`}>
          For the purpose of these Terms of Use, wherever the context so
          requires "you", "your" or "user" shall mean any natural or legal
          person who has agreed to become a user/buyer on the Platform.
        </Text>

        <Text style={tw`text-xl font-semibold text-black dark:text-white mt-8 mb-4`}>
          Important Notes:
        </Text>
        <Text style={tw`text-black dark:text-white leading-7`}>
          • ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
          AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE
          {'\n\n'}• You agree to provide true, accurate and complete information
          {'\n\n'}• Your use of our Services is solely at your own risk{'\n\n'}• You
          agree not to use the Platform for any unlawful purpose{'\n\n'}• You
          agree to pay us the charges associated with availing the Services
        </Text>

        <Text style={tw`text-xl font-semibold text-black dark:text-white mt-8 mb-4`}>
          Jurisdiction
        </Text>
        <Text style={tw`text-black dark:text-white leading-6`}>
          These Terms and any dispute or claim relating to it, or its
          enforceability, shall be governed by and construed in accordance with
          the laws of India. All disputes arising out of or in connection with
          these Terms shall be subject to the exclusive jurisdiction of the
          courts in {jurisdiction}.
        </Text>

        <Text style={tw`text-xl font-semibold text-black dark:text-white mt-8 mb-4`}>
          Contact
        </Text>
        <Text style={tw`text-black dark:text-white leading-6 mb-8`}>
          All concerns or communications relating to these Terms must be
          communicated to us at {contactEmail}.
        </Text>
      </View>
    </ScrollView>
  );
};

export default TncContainer;
